// frontend/src/store/actions/systemTypes.js
export const FETCH_REDIS_CACHE = "FETCH_REDIS_CACHE";
export const FETCH_REDIS_CACHE_SUCCESS = "FETCH_REDIS_CACHE_SUCCESS";
export const FETCH_REDIS_CACHE_FAILURE = "FETCH_REDIS_CACHE_FAILURE";

export const FETCH_RABBITMQ_STATUS = "FETCH_RABBITMQ_STATUS";
export const FETCH_RABBITMQ_STATUS_SUCCESS = "FETCH_RABBITMQ_STATUS_SUCCESS";
export const FETCH_RABBITMQ_STATUS_FAILURE = "FETCH_RABBITMQ_STATUS_FAILURE";

export const FETCH_EVENT_LOG = "FETCH_EVENT_LOG";
export const FETCH_EVENT_LOG_SUCCESS = "FETCH_EVENT_LOG_SUCCESS";
export const FETCH_EVENT_LOG_FAILURE = "FETCH_EVENT_LOG_FAILURE";

export const FETCH_SYSTEM_HEALTH = "FETCH_SYSTEM_HEALTH";
export const FETCH_SYSTEM_HEALTH_SUCCESS = "FETCH_SYSTEM_HEALTH_SUCCESS";
export const FETCH_SYSTEM_HEALTH_FAILURE = "FETCH_SYSTEM_HEALTH_FAILURE";

export const START_POLLING = "START_POLLING";
export const STOP_POLLING = "STOP_POLLING";
