// Task Action Types

export const TASK_FETCH_REQUEST = "TASK/FETCH_REQUEST";
export const TASK_FETCH_SUCCESS = "TASK/FETCH_SUCCESS";
export const TASK_FETCH_FAILURE = "TASK/FETCH_FAILURE";

export const TASK_CREATE_REQUEST = "TASK/CREATE_REQUEST";
export const TASK_CREATE_SUCCESS = "TASK/CREATE_SUCCESS";
export const TASK_CREATE_FAILURE = "TASK/CREATE_FAILURE";

export const TASK_UPDATE_STATUS_REQUEST = "TASK/UPDATE_STATUS_REQUEST";
export const TASK_UPDATE_STATUS_SUCCESS = "TASK/UPDATE_STATUS_SUCCESS";
export const TASK_UPDATE_STATUS_FAILURE = "TASK/UPDATE_STATUS_FAILURE";

export const TASK_DELETE_REQUEST = "TASK/DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK/DELETE_SUCCESS";
export const TASK_DELETE_FAILURE = "TASK/DELETE_FAILURE";
